### ISSUE TITLE
difficulty-3/redesign interview card according to the new wireframe (1 Day)

### ISSUE THREAD

**Issue by ranegray** [gschool-blue-ocean/admissions-hub-20#23]
see figma file: https://github.com/gschool-blue-ocean/admissions-hub-20/issues/23#issue-1749725634

![Screenshot 2023-06-09 at 14 56 46](https://github.com/gschool-blue-ocean/admissions-hub-20/assets/75066470/289c3178-0d32-482d-a80c-15a45e7f827a)

this one might take a little bit longer. we need to refactor the UI and probably a lot of the state to make the wireframe work.

you can hard code some of the data that isn't in the ERD if you please.

**Comment by DanielPurdy509** [comment]
Update:

- Originally planned on refactoring old interview card / interface which relies upon data from the server
- Have run into issue where GET requests fail without much context, possibly due to inconsistencies with dependencies, docker container not being set up properly, or something else.
- Using hard coded data to work around the issue for the moment to in order keep working on new design for the interview card.
- Planning on getting help from Joe to look over my dev environment to try and resolve the issue with requests failing.
